import turtle
amy = turtle.Turtle()
amy.color("red")
amy.forward(100)
amy.right(90)
amy.color("yellow")
amy.forward(100)
amy.right(90)
amy.color("golden")
amy.forward(100)
amy.right(90)
amy.color("green")
amy.forward(100)